version: '3.8'

services:
  db:
    image: postgres:15
    container_name: iris-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: iris-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db