apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-app
  template:
    metadata:
      labels:
        app: iris-app
    spec:
      containers:
      - name: iris-app
        image: 018946425539.dkr.ecr.us-east-1.amazonaws.com/iris-app:latest # <- ezt le kell cserélni a jóra
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: iris-db.ced408uogkjx.us-east-1.rds.amazonaws.com # <-- Ezt majd az RDS adatbázis címmel töltöm ki!
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "postgres"
        - name: JWT_SECRET
          value: "superTitkosTokenKulcs123!"
